openapi: 3.0.0
info:
  title: Online Store Dashboard Service
  version: 1.0.0
  description: Dashboard service for online store app
paths:
  "/users/login":
    post:
      tags:
      - Users
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Login"
            example:
              email: example@mail.com
              password: password
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
              example:
                message: login success
                success: true
                data:
                  accessToken: "token"
                  refreshToken: "token"
        404:
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  data:
                    type: object
                    properties: {}
              example:
                message: user not found
                success: false
                data: {}
        403:
          description: forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  data:
                    type: object
                    properties: {}
              example:
                message: wrong password
                success: false
                data: {}
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          nullable: false
          minLength: 1
        password:
          type: string
          nullable: false
          minLength: 8
